apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "openfga-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openfga-operator
    app.kubernetes.io/part-of: openfga-operator
  {{- include "openfga-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "openfga-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "openfga-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
