apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openfga-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openfga-operator
    app.kubernetes.io/part-of: openfga-operator
  {{- include "openfga-operator.labels" . | nindent 4 }}
