# permissions for end users to view natsusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: natsuser-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openfga-operator
    app.kubernetes.io/part-of: openfga-operator
    app.kubernetes.io/managed-by: kustomize
  name: natsuser-viewer-role
rules:
  - apiGroups:
      - openfga.zeiss.com
    resources:
      - natsusers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - openfga.zeiss.com
    resources:
      - natsusers/status
    verbs:
      - get
